### ISSUE TITLE
Default range in FilterPane would prevent new entries beyond that range from being fetched from API in Source List

### ISSUE THREAD

**Issue by tszwinglitw** [Su24-CS5004-Online-Lionelle/final-project-group-5#18]

**Comment by jackeinbinder01** [comment]
Just pushed an update that should clear placeholders in the event that the source list is passed to setMovies(). This requires a second bool arg that defaults to false, so if you pass the source list use setMovies(sourceList, true);

Pls review on your end and close the issue if you are getting the expected behavior
